### ISSUE TITLE
`Clock::new` overhead

### ISSUE THREAD

**Issue by jstrong-tios** [nuclearfurnace/quanta#2]
Awesome work on this library!

I want to preface this question by acknowledging that anyone who is using quanta is probably not creating a new clock instance except at the beginning of their program. Also, I'm mostly out of curiosity since this is a pretty trivial problem. However, I was somewhat surprised at the relatively long startup time on the first initialization. Is this wholly unavoidable or is there a possibility of declaring a clock `const` or `static` to fold the initialization cost into program startup? Is the time spent recording multiple clock measurements for calibration purposes or is there any actual computational overhead to it?

**Comment by tobz** [comment]
The time spent is purely in calibration.  It basically runs a tight loop of reference calls -- which would be something like `clock_gettime(CLOCK_MONOTONIC)` on Linux -- until a certain amount of time has passed.

We could definitely expose the calibration data so that a one-time calibration run could be collected within, say, a lazy static, and then use for future clock creations.

We'd probably also want to allow configuring the calibration time because right now it ends up being around a second, based on the default values.

Thinking about it now, that was definitely a suboptimal amount of time to bake in that isn't communicated well to users.  Sorry about that!

**Comment by tobz** [comment]
Follow-up: I haven't totally followed the `const fn` progression, but I don't think could make `Clock` itself `const` capable, because of the current limitations of what constant functions can do.

Thinking it through a little, I'm not even sure if you could reasonably run the calibration sequence in a constant context because like.. what happens when you cross-compile and you want Windows timing primitives but you're compiling on macOS? etc etc

Being able to expose calibration so it could be `lazy_static`'d still stands, though.

**Comment by jstrong-tios** [comment]
I ended up using lazy static in my case. It's a good solution. I also benchmarked and found no measurable difference in time between calling a `Clock` wrapped in `lazy_static!` and one without. 

Makes sense about `const fn` - thanks for the quick and thorough reply!

**Comment by tobz** [comment]
Cool, glad you found a workable solution!

Gonna close this out.  If you have any issues, or suggestions, feel free to let me know. :)
